defaults: &defaults
  adapter: mysql
  encoding: utf8
  username: root
  password: os1ol3k
  socket: /var/run/mysqld/mysqld.sock

development:
  database: worktime_development
  <<: *defaults

test:
  database: worktime_test 
  <<: *defaults

production:
  database: worktime_production
  <<: *defaults
